USE sushi_db;
INSERT INTO food (price, rollName, category, quantity, createdAt, updatedAt) VALUES ('6', 'Tuna', 'sushi', '0', NOW(), NOW());
INSERT INTO food (price, rollName, category, quantity, createdAt, updatedAt) VALUES ('6', 'Tuna Belly', 'sushi', '0', NOW(), NOW());
INSERT INTO food (price, rollName, category, quantity, createdAt, updatedAt) VALUES ('6', 'Yellowtail', 'sushi', '0', NOW(), NOW());
INSERT INTO food (price, rollName, category, quantity, createdAt, updatedAt) VALUES ('6', 'Salmon', 'sushi', '0', NOW(), NOW());
INSERT INTO food (price, rollName, category, quantity, createdAt, updatedAt) VALUES ('6', 'Octopus', 'sushi', '0', NOW(), NOW());
INSERT INTO food (price, rollName, category, quantity, createdAt, updatedAt) VALUES ('7', 'Fresh Water Eel', 'sushi', '0', NOW(), NOW());
INSERT INTO food (price, rollName, category, quantity, createdAt, updatedAt) VALUES ('6', 'Salt Water Eel', 'sushi', '0', NOW(), NOW());
INSERT INTO food (price, rollName, category, quantity, createdAt, updatedAt) VALUES ('12', 'Sea Urchin', 'sushi', '0', NOW(), NOW());
INSERT INTO food (price, rollName, category, quantity, createdAt, updatedAt) VALUES ('7', 'Shrimp', 'sushi', '0', NOW(), NOW());
INSERT INTO food (price, rollName, category, quantity, createdAt, updatedAt) VALUES ('9', 'Sweet Shrimp', 'sushi', '0', NOW(), NOW());
INSERT INTO food (price, rollName, category, quantity, createdAt, updatedAt) VALUES ('6', 'Smoked Salmon', 'sushi', '0', NOW(), NOW());
INSERT INTO food (price, rollName, category, quantity, createdAt, updatedAt) VALUES ('13', 'Vegi Vegi', 'Maki', '0', NOW(), NOW());
INSERT INTO food (price, rollName, category, quantity, createdAt, updatedAt) VALUES ('15', 'Rainbow', 'Maki', '0', NOW(), NOW());
INSERT INTO food (price, rollName, category, quantity, createdAt, updatedAt) VALUES ('15', 'Caterpillar', 'Maki', '0', NOW(), NOW());
INSERT INTO food (price, rollName, category, quantity, createdAt, updatedAt) VALUES ('15', 'Soft Shell Crab', 'Maki', '0', NOW(), NOW());
INSERT INTO food (price, rollName, category, quantity, createdAt, updatedAt) VALUES ('15', 'Futomaki', 'Maki', '0', NOW(), NOW());
INSERT INTO food (price, rollName, category, quantity, createdAt, updatedAt) VALUES ('15', 'Double Dragon', 'Maki', '0', NOW(), NOW());
INSERT INTO food (price, rollName, category, quantity, createdAt, updatedAt) VALUES ('15', 'Sake Kani', 'Maki', '0', NOW(), NOW());
INSERT INTO food (price, rollName, category, quantity, createdAt, updatedAt) VALUES ('15', 'Big Eye Diver', 'Maki', '0', NOW(), NOW());
INSERT INTO food (price, rollName, category, quantity, createdAt, updatedAt) VALUES ('15', 'Tempura Crunchy', 'Maki', '0', NOW(), NOW());
INSERT INTO food (price, rollName, category, quantity, createdAt, updatedAt) VALUES ('15', 'Ahi Tuna Tataki', 'Maki', '0', NOW(), NOW());
INSERT INTO food (price, rollName, category, quantity, createdAt, updatedAt) VALUES ('15', 'Poki Poki', 'Maki', '0', NOW(), NOW());
/* -------------------------------------------------------------------------------------------- */
USE sushi_db;
/* INSERT INTO orders (rollName, quantity, tablenumber) VALUES ('Tuna', '1', '1');
INSERT INTO orders (rollName, quantity, tablenumber) VALUES ('Vegi Vegi', '2', '2');
INSERT INTO orders (rollName, quantity, tablenumber) VALUES ('Ahi Tuna Tataki', '1', '2');
INSERT INTO orders (rollName, quantity, tablenumber) VALUES ('Double Dragon', '3', '3');
INSERT INTO orders (rollName, quantity, tablenumber) VALUES ('Shrimp', '1', '4');
INSERT INTO orders (rollName, quantity, tablenumber) VALUES ('Caterpillar', '4', '4');
INSERT INTO orders (rollName, quantity, tablenumber) VALUES ('Big Eye Diver', '2', '2');
INSERT INTO orders (rollName, quantity, tablenumber) VALUES ('Octopus', '1', '1');
INSERT INTO orders (rollName, quantity, tablenumber) VALUES ('Salmon', '1', '3'); */
SELECT * FROM orders;