INSERT INTO food (price, rollName, category) VALUES ('6, Tuna, sushi');
INSERT INTO food (price, rollName, category) VALUES ('6, Tuna Belly, sushi');
INSERT INTO food (price, rollName, category) VALUES ('6, Yellowtail, sushi');
INSERT INTO food (price, rollName, category) VALUES ('6, Salmon, sushi');
INSERT INTO food (price, rollName, category) VALUES ('6, Octopus, sushi');
INSERT INTO food (price, rollName, category) VALUES ('7, Fresh Water Eel, sushi');
INSERT INTO food (price, rollName, category) VALUES ('6, Salt Water Eel, sushi');
INSERT INTO food (price, rollName, category) VALUES ('6, Tuna, sushi');
INSERT INTO food (price, rollName, category) VALUES ('12, Sea Urchin, sushi');
INSERT INTO food (price, rollName, category) VALUES ('7, Shrimp, sushi');
INSERT INTO food (price, rollName, category) VALUES ('9, Sweet Shrimp, sushi');
INSERT INTO food (price, rollName, category) VALUES ('6, Smoked Salmon, sushi');
INSERT INTO food (price, rollName, category) VALUES ('13, Vegi Vegi, Maki');
INSERT INTO food (price, rollName, category) VALUES ('15, Rainbow, Maki');
INSERT INTO food (price, rollName, category) VALUES ('15, Caterpillar, Maki');
INSERT INTO food (price, rollName, category) VALUES ('15, Soft Shell Crab, Maki');
INSERT INTO food (price, rollName, category) VALUES ('15, Futomaki, Maki');
INSERT INTO food (price, rollName, category) VALUES ('15, Double Dragon, Maki');
INSERT INTO food (price, rollName, category) VALUES ('15, Sake Kani, Maki');
INSERT INTO food (price, rollName, category) VALUES ('15, Big Eye Diver, Maki');
INSERT INTO food (price, rollName, category) VALUES ('15, Tempura Crunchy, Maki');
INSERT INTO food (price, rollName, category) VALUES ('15, Ahi Tuna Tataki, Maki');
INSERT INTO food (price, rollName, category) VALUES ('15, Poki Poki, Maki');
/* -------------------------------------------------------------------------------------------- */
INSERT INTO order (rollName, quantity, tablenumber) VALUES ('Tuna, 1, 1');
INSERT INTO order (rollName, quantity, tablenumber) VALUES ('Vegi Vegi, 2, 2');
INSERT INTO order (rollName, quantity, tablenumber) VALUES ('Ahi Tuna Tataki, 1, 2');
INSERT INTO order (rollName, quantity, tablenumber) VALUES ('Double Dragon, 3, 3');
INSERT INTO order (rollName, quantity, tablenumber) VALUES ('Shrimp, 1, 4');
INSERT INTO order (rollName, quantity, tablenumber) VALUES ('Caterpillar, 4, 4');
INSERT INTO order (rollName, quantity, tablenumber) VALUES ('Big Eye Diver, 2, 2');
INSERT INTO order (rollName, quantity, tablenumber) VALUES ('Octopus, 1, 1');
INSERT INTO order (rollName, quantity, tablenumber) VALUES ('Salmon, 1, 3');